/****** Object:  Table [dbo].[UlkeTelefonKodlari]    Script Date: 8.01.2022 16:04:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UlkeTelefonKodlari](
	[Id] [int] NOT NULL,
	[UlkeKodu] [nvarchar](50) NULL,
	[UlkeAdi] [nvarchar](50) NULL,
 CONSTRAINT [PK_UlkeTelefonKodlari] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (1, N'+90', N'Türkiye')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (2, N'+49', N'Almanya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (3, N'+33', N'Fransa')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (4, N'+7', N'Rusya Federasyonu')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (5, N'+39', N'İtalya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (6, N'+1', N'Amerika Birleşik Devletleri')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (7, N'+30', N'Yunanistan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (8, N'+31', N'Hollanda')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (9, N'+32', N'Belçika')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (10, N'+7', N'Kazakistan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (11, N'+34', N'İspanya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (12, N'+994', N'Azerbaycan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (13, N'+20', N'Mısır')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (14, N'+40', N'Romanya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (15, N'+41', N'İsviçre')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (16, N'+43', N'Avusturya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (17, N'+44', N'İngiltere')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (18, N'+45', N'Danimarka')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (19, N'+46', N'İsveç')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (20, N'+47', N'Norveç')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (21, N'+48', N'Polonya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (22, N'+1', N'Kanada')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (23, N'+52', N'Meksika')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (24, N'+54', N'Arjantin')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (25, N'+55', N'Brezilya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (26, N'+60', N'Malezya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (27, N'+61', N'Avustralya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (28, N'+62', N'Endonezya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (29, N'+64', N'Yeni Zelanda')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (30, N'+66', N'Tayland')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (31, N'+81', N'Japonya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (32, N'+82', N'Güney Kore')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (33, N'+86', N'Çin Halk Cumhuriyeti')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (34, N'+27', N'Güney Afrika Cumhuriyeti')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (35, N'+91', N'Hindistan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (36, N'+92', N'Pakistan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (37, N'+93', N'Afganistan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (38, N'+98', N'İran')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (39, N'+212', N'Fas')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (40, N'+213', N'Cezayir')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (41, N'+216', N'Tunus')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (42, N'+218', N'Libya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (43, N'+237', N'Kamerun')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (44, N'+350', N'Cebelitarık')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (45, N'+351', N'Portekiz')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (46, N'+352', N'Lüksemburg')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (47, N'+353', N'İrlanda')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (48, N'+354', N'İzlanda')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (49, N'+355', N'Arnavutluk')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (50, N'+356', N'Malta')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (51, N'+357', N'Güney Kıbrıs Rum Yönetimi')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (52, N'+358', N'Finlandiya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (53, N'+359', N'Bulgaristan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (54, N'+370', N'Litvanya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (55, N'+371', N'Letonya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (56, N'+372', N'Estonya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (57, N'+373', N'Moldova')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (58, N'+375', N'Beyaz Rusya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (59, N'+376', N'Andorra')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (60, N'+377', N'Monako')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (61, N'+378', N'San Marino')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (62, N'+380', N'Ukrayna')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (63, N'+381', N'Karadağ')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (64, N'+385', N'Hırvatistan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (65, N'+386', N'Slovenya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (66, N'+387', N'Bosna Hersek')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (67, N'+389', N'Makedonya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (68, N'+392', N'Kuzey Kıbrıs Türk Cumhuriyeti')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (69, N'+420', N'Çek Cumhuriyeti')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (70, N'+421', N'Slovak Cumhuriyeti')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (71, N'+423', N'Lihtenştayn')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (72, N'+507', N'Panama')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (73, N'+850', N'Kuzey Kore')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (74, N'+852', N'Hong Kong')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (75, N'+853', N'Makao')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (76, N'+855', N'Kamboçya')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (77, N'+856', N'Lao Demokratik Halk Cumhuriyeti')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (78, N'+880', N'Bangladeş')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (79, N'+886', N'Tayvan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (80, N'+960', N'Maldiv Adaları')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (81, N'+961', N'Lübnan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (82, N'+962', N'Urdun')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (83, N'+963', N'Suriye')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (84, N'+964', N'Irak')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (85, N'+965', N'Kuveyt')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (86, N'+966', N'Suudi Arabistan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (87, N'+967', N'Yemen Arap Cumhuriyeti')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (88, N'+968', N'Umman')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (89, N'+970', N'Filistin')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (90, N'+971', N'Birleşik Arap Emirlikleri')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (91, N'+973', N'Bahreyn')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (92, N'+974', N'Katar')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (93, N'+975', N'Butan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (94, N'+976', N'Moğolistan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (95, N'+977', N'Nepal')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (96, N'+992', N'Tacikistan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (97, N'+993', N'Türkmenistan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (98, N'+36', N'Macaristan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (99, N'+995', N'Gürcistan')
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (100, N'+996', N'Kırgızistan')
GO
INSERT [dbo].[UlkeTelefonKodlari] ([Id], [UlkeKodu], [UlkeAdi]) VALUES (101, N'+998', N'Özbekistan')
GO
